import React from "react";
import SummaryDisplay from "../ui/SummaryDIsplay";

const UploadSummary = () => {
  return (
    <main className="flex flex-row justify-center p-4 items-center w-full h-full bg-customBlack">
      <section className="flex-1 h-full w-full">
        <SummaryDisplay />
      </section>
      <section className="flex-1 h-full flex flex-col justify-between pt-40 py-5 items-center ">
        <div className="flex flex-col space-y-5 justify-center items-center text-center">
          <h3 className="font-semibold text-4xl">Document Summary</h3>
          <p className="text-sm font-light">
            This Document summary is Generated by{" "}
            <span className="text-teal-400 font-normal">Adira AI.</span>
            Download your Document summary and Use it for your reference.
          </p>
        </div>
        {/* buttons */}

        <div className="flex flex-row justify-center items-center w-full space-x-5">
          <button className="bg-card-gradient  text-white font-bold p-3 px-10 rounded-md">Go Back</button>
          <button className="bg-card-gradient   text-white font-bold p-3 px-10 rounded-md">Download</button>


        </div>
      </section>
    </main>
  );
};

export default UploadSummary;
